POST http://localhost:7070/api/auth/register
Content-Type: application/json

{
"username":"user6",
"password":"p1234"
}

###
POST http://localhost:7070/api/auth/login
Content-Type: application/json

{
"username":"user6",
"password":"p1234"
}

###
GET http://localhost:7070/api/secured/demo
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIkNhc3BlciBHZXJ2aWdcIiIsInN1YiI6InVzZXI2IiwiZXhwIjoxNzQyMTQxNTY0LCJyb2xlcyI6InVzZXIiLCJ1c2VybmFtZSI6InVzZXI2In0.Qo0ZM6zf5PN-n_LhK5RA3O0cWeiXa2JWA-F2RbVLl3Y
